apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlq-handler
  namespace: kafka-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dlq-handler
  template:
    metadata:
      labels:
        app: dlq-handler
    spec:
      serviceAccountName: dlq-handler-sa
      containers:
        - name: dlq-handler
          image: 'ghcr.io/bonge0115/dlq-handler:5882d91' # 이미지 수정 
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP
              value: kafka.kafka-poc.svc.cluster.local:9092
            - name: DLQ_TOPIC
              value: orders-dlq
            - name: GROUP_ID
              value: orders-dlq-handler
            - name: ENABLE_REPLAY
              value: "false"
            - name: ENABLE_GITHUB_DISPATCH
              value: "true"
            - name: GITHUB_OWNER
              value: "BongE0115"
            - name: GITHUB_REPO
              value: "Zero-Trust-IDP"
            - name: GITHUB_WORKFLOW_FILE
              value: "activate-sandbox.yaml"
            - name: GITHUB_REF
              value: "jy"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-dispatch-secret
                  key: token
            - name: TOPIC_INIT_IMAGE
              value: bitnamilegacy/kafka:3.7
