apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka-poc

resources:
  - 00-namespace.yaml
  - 01-kafka.yaml
  - 02-topics-job.yaml
  - 11-producer.yaml
  - 21-consumer.yaml
  - 30-dlq-handler-rbac.yaml
  - 32-dlq-handler.yaml