apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice:v0.10.5
        # 🔥 추가됨: Kafka Consumer 1 & 에러 발생 시 명세서를 보낼 DLQ 설정
        env:
        - name: KAFKA_BROKER_URL
          value: "kafka.default.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "orders"
        - name: DLQ_TOPIC
          value: "orders-dlq"
        - name: DISABLE_PROFILER # 🔥 이 줄을 추가하세요!
          value: "1"
---
# shippingservice는 원본 그대로 사용 (AWS 내부에서 단독 동작)
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  selector:
    app: shippingservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.5