apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: sandbox-waypoint
  namespace: forensic-sandbox
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    istio.io/waypoint-for: all
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE