apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: NodePort # 🔥 외부(AWS) 호출을 위해 NodePort로 변경
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
    nodePort: 30002 # 🔥 프론트엔드 환경변수와 일치시킴
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.5
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
---
# (redis-cart는 로컬 cartservice만 호출하므로 ClusterIP 유지)
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  selector:
    app: redis-cart
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis
        image: redis:alpine