apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  type: NodePort  #  ClusterIP에서 NodePort로 변경
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
    nodePort: 30550 # 고정 포트 할당
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.5
        ports:
        - containerPort: 3550