apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sandbox-defense-in-depth
  namespace: forensic-sandbox  #
  annotations:
    # ★ [추가] 2순위: 샌드박스 앱(Wave 1)이 뜨기 전에 물리적 방화벽을 먼저 세팅합니다.
    argocd.argoproj.io/sync-wave: "0"
spec:
  podSelector:
    matchLabels:
      app: forensic-sandbox-app  #
  policyTypes:
  - Egress  #
  # [나가는 트래픽 제어]
  egress:  #
  # 1. 내부 Kafka (DLQ 토픽 접근 허용)
  # ★ [수정] Kafka는 다른 네임스페이스('kafka')에 있고, Strimzi 오퍼레이터의 라벨을 따르므로 수정이 필수입니다!
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kafka-poc # 최종적으로 poc를 제거해야 됨
      podSelector:
        matchLabels:
          app: kafka
    ports:
    - protocol: TCP
      port: 9092
      
  # 2. 내부 임시 MongoDB (샌드박스 DB 접근 허용)
  - to:
    - podSelector:
        matchLabels:
          app: mongodb-temp  #
    ports:
    - protocol: TCP  #
      port: 27017  #
      
  # 3. K8s DNS 통신 허용 (이게 없으면 호스트명을 IP로 못 찾아서 에러남)
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system  #
      podSelector:
        matchLabels:
          k8s-app: kube-dns  #
    ports:
    - protocol: UDP  #
      port: 53  #
  
  # ★ [수정] AWS RDS IP 대역으로 향하는 5432(PostgreSQL) 포트 트래픽은 이 화이트리스트에 없으므로 CNI 단에서 물리적 Drop 처리됨.