# 1. 앰비언트 메시 라벨이 적용된 네임스페이스 (★ 누락됐던 핵심 부분 복구!)
apiVersion: v1
kind: Namespace
metadata:
  name: forensic-sandbox
  labels:
    # 파드 트래픽을 노드의 ztunnel이 가로채도록 설정
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: sandbox-waypoint
    # 깃옵스 기반 온-디멘드 샌드박스 완전 구현을 위해 샌드박스 생성 및 istio 보안 규칙 순서 동기화 wave 추가
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
# 2. 전용 Service Account 생성 (신분증)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-app-sa
  namespace: forensic-sandbox
  # 깃옵스 기반 온-디멘드 샌드박스 완전 구현을 위해 샌드박스 생성 및 istio 보안 규칙 순서 동기화 wave 추가
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forensic-sandbox-app
  namespace: forensic-sandbox
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 0
  selector:
    matchLabels:
      app: forensic-sandbox-app
  template:
    metadata:
      labels:
        app: forensic-sandbox-app
    spec:
      serviceAccountName: sandbox-app-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: consumer-app
        image: ghcr.io/bonge0115/worker-consumer:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: KAFKA_BOOTSTRAP
          value: "kafka.kafka-poc.svc.cluster.local:9092"
        - name: SOURCE_TOPIC
          value: "orders-replay"
        - name: DLQ_TOPIC
          value: "orders-dlq"
        - name: GROUP_ID
          value: "orders-consumer-sandbox"

        - name: SERVICE_NAME
          value: "forensic-sandbox-app"
        - name: NAMESPACE
          value: "forensic-sandbox"
        - name: DEPLOYMENT_NAME
          value: "forensic-sandbox-app"

        - name: IMAGE_REF
          value: "ghcr.io/bonge0115/worker-consumer:latest"
        - name: CONFIG_VERSION
          value: "sandbox-v1"
        - name: DEPENDENCY_PROFILE
          value: "sandbox"

        - name: DB_MODE
          value: "mongo"
        - name: DB_HOST
          value: "mongodb-temp.forensic-sandbox.svc.cluster.local"

        - name: CACHE_MODE
          value: "mock"
        - name: CACHE_HOST
          value: ""

        - name: EXTERNAL_API_MODE
          value: "mock"
        - name: EXTERNAL_API_BASE_URL
          value: ""

        - name: FORCE_FAIL_FIELD
          value: "should_fail"