apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 배포할 파일 목록
resources:
  - 00-namespace.yaml
  - zookeeper.yaml
  - kafka.yaml

# 모든 리소스에 공통으로 적용될 네임스페이스
namespace: kafka

# 공통 라벨 설정 (ArgoCD에서 관리하는 리소스 식별용)
commonLabels:
  app.kubernetes.io/managed-by: argocd
  stack: kafka-bi-stack
