# 1. Istio에게 "저 멀리 외부에 AWS RDS가 있다"고 알려주는 ServiceEntry
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: aws-rds-external
  namespace: forensic-sandbox
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Wave 0 유지
spec:
  hosts:
  - "aws-rds-host" # AWS RDS 엔드포인트
  ports:
  - number: 5432      # ★ 3306(MySQL)에서 5432(PostgreSQL)로 수정
    name: tcp-postgres # ★ 이름도 역할에 맞게 변경
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: DNS

---
# 2. 샌드박스 앱이 AWS RDS로 나가는 것을 '무조건 거부(DENY)'하는 AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-aws-rds-egress
  namespace: forensic-sandbox
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Wave 0 유지
spec:
  selector:
    matchLabels:
      app: forensic-sandbox-app # 샌드박스 컨슈머 파드만 타겟팅
  action: DENY # ★ 차단!
  rules:
  - to:
    - operation:
        # hosts: ["aws-rds-host"] # yaml 파일은 쉘 스크립트 같은 환경 변수 치환을 못함. 
        ports: ["5432"] # ★ 차단할 포트 번호도 5432로 수정