apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: block-aws-rds-egress
  namespace: forensic-sandbox
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  hosts:
  - aws-rds-host 
  location: MESH_EXTERNAL
  ports:
  - number: 5432
    name: tcp-db
    protocol: TCP
  resolution: STATIC
  endpoints:
  - address: 127.0.0.254