apiVersion: v1
kind: ServiceAccount
metadata:
  name: dlq-handler-sa
  namespace: kafka-poc # 네임스페이스가 kafka-poc인 애가 샌드박스, 몽고 레플리카 0->1로 승격시킴
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dlq-handler-role
  namespace: forensic-sandbox
rules:
  - apiGroups: ["apps"]
    resources: ["deployments","deployments/scale"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dlq-handler-rb
  namespace: forensic-sandbox
subjects:
  - kind: ServiceAccount
    name: dlq-handler-sa
    namespace: kafka-poc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dlq-handler-role