apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: strimzi-kafka-operator
  namespace: kube-system
spec:
  repo: https://strimzi.io/charts/
  chart: strimzi-kafka-operator
  version: 0.46.1
  targetNamespace: kafka
  createNamespace: false
  valuesContent: |-
    replicas: 1
    watchAnyNamespace: false
    watchNamespaces:
      - kafka

# 대신 안정적인 구동을 위해 넉넉한 자원(메모리)을 할당합니다.
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1Gi